-- CreateTable
CREATE TABLE `Pond` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `deviceId` VARCHAR(191) NOT NULL,
    `address` VARCHAR(191) NOT NULL,
    `city` VARCHAR(191) NOT NULL,
    `seedDate` DATETIME(3) NULL,
    `tempUpper` INTEGER NOT NULL DEFAULT 30,
    `tempLower` INTEGER NOT NULL DEFAULT 28,
    `hmdUpper` INTEGER NOT NULL DEFAULT 70,
    `hmdLower` INTEGER NOT NULL DEFAULT 80,
    `phUpper` DECIMAL(65, 30) NOT NULL DEFAULT 9,
    `phLower` DECIMAL(65, 30) NOT NULL DEFAULT 6.5,
    `tdoUpper` INTEGER NOT NULL DEFAULT 8,
    `tdoLower` INTEGER NOT NULL DEFAULT 4,
    `salUpper` INTEGER NOT NULL DEFAULT 25,
    `salLower` INTEGER NOT NULL DEFAULT 15,
    `fcrUpper` DECIMAL(65, 30) NOT NULL DEFAULT 1.5,
    `fcrLower` DECIMAL(65, 30) NOT NULL DEFAULT 1.2,
    `status` VARCHAR(191) NOT NULL DEFAULT 'baik',
    `userId` INTEGER NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Pond` ADD CONSTRAINT `Pond_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
